Feature/fix sessionstack plugin event preprocessing issues
getsentry/sentry-plugins pull request #139
Opened 2017-03-04 18:05 UTC by lsnickolov

2017-03-07 15:40 UTC, mitsuhiko requested changes

2017-03-07 15:40 UTC, mitsuhiko commented on src/sentry_plugins/sessionstack/plugin.py
> +        project = Project.objects.get_from_cache(id=data.get('project'))
Can you move this one down to be the last check? This will still cause a network roundtrip and the rest does not.

2017-03-07 15:46 UTC, lsnickolov commented on src/sentry_plugins/sessionstack/plugin.py
> +        project = Project.objects.get_from_cache(id=data.get('project'))
Sure. Will do that.

2017-03-24 15:22 UTC, mitsuhiko approved these changes

2017-03-27 07:42 UTC, merged